name: Build and Test

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.12.0'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.4'

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
      with:
        mongodb-version: '4.4'

    - name: Install frontend dependencies
      run: |
        cd frontend
        npm install

    - name: Install backend dependencies
      run: |
        pip install -r requirements.txt

    - name: Start frontend application
      run: |
        cd frontend
        nohup node app.js > frontend.log 2>&1 &

    - name: Run backend tests
      run: | 
        nohup python app.py > backend.log 2>&1 &

    - name: Wait for applications to start
      run: |
        timeout 60 bash -c 'while ! curl --fail http://localhost:8001; do sleep 2; done'
        timeout 60 bash -c 'while ! curl --fail http://localhost:3000; do sleep 2; done'

    - name: Check webserver on port 8001
      run: |
        curl --fail http://localhost:8001 || exit 1

    - name: Check Python API on port 3000
      run: |
        curl --fail http://localhost:3000 || exit 1
